/// Generated by AssetsRefGenerator on 2020/03/07



class Res {
  static const String CustomIcons = "assets/font/CustomIcons.ttf";
  static const String kollektif = "assets/font/kollektif.ttf";
  static const String kollektif_bold = "assets/font/kollektif_bold.ttf";
  static const String kollektif_bolditalic = "assets/font/kollektif_bolditalic.ttf";
  static const String kollektif_iitalic = "assets/font/kollektif_iitalic.ttf";
  static const String ic_logo = "assets/images/ic_logo.png";
  static const String ic_intro = "assets/images/intro.png";
  static const String ic_google = "assets/images/ic_google.png";
  static const String ic_facebook = "assets/images/ic_facebook.png";
  static const String ic_back = "assets/images/ic_back.png";
  static const String ic_profile = "assets/images/ic_profile.png";
  static const String ic_male = "assets/images/ic_male.png";
  static const String ic_male_new = "assets/images/ic_male_new.png";
  static const String ic_female = "assets/images/ic_female.png";
  static const String ic_notification = "assets/images/ic_notification.png";
  static const String ic_right_arrow = "assets/images/ic_right_arrow.png";
  static const String ic_tint = "assets/images/ic_tint.png";
  static const String ic_add_card = "assets/images/ic_add_card.jpg";
  static const String ic_setting = "assets/images/ic_setting.png";
  static const String emailSent = "assets/images/emailSent.png";
  static const String maleUnselectet = "assets/images/maleUnselectet.png";
  static const String femaleUnselected = "assets/images/femaleUnselected.png";

  static const String profile = 'assets/images/profile.png';
  static const String track = 'assets/images/track.png';
  static const String foodDiary = 'assets/images/foodDiary.png';
  static const String goals = 'assets/images/goals.png';
  static const String workouts = 'assets/images/workouts.png';

  static const String selctedWorkouts =  'assets/images/selctedWorkouts.png';
  static const String selectedProfile =  'assets/images/selectedProfile.png';
  static const String selectedTrac =  'assets/images/selectedTrac.png';
  static const String selectedFoodDiary =  'assets/images/selectedFoodDiary.png';
  static const String selectedGoals =  'assets/images/selectedGoals.png';
  static const String notifications =  'assets/images/notifications.png';

  static const String upper =  'assets/images/upper.png';
  static const String fullBody =  'assets/images/fullBody.png';
  static const String core =  'assets/images/core.png';
  static const String lowerBody =  'assets/images/lowerBody.png';
  static const String quete =  'assets/images/quete.png';
  static const String play =  'assets/images/play.png';
  static const String ImageThumbnailVideo =  'assets/images/ImageThumbnailVideo.png';
  static const String upNext =  'assets/images/upNext.png';
  static const String pause =  'assets/images/pause.png';
  static const String play_button =  'assets/images/play-button.png';
  static const String goalList =  'assets/images/goalList.png';
  static const String add_Image =  'assets/images/add_Image.png';

  static const String selectedGoalsDetails =  'assets/images/selectedGoalsDetails.png';
  static const String unselectedGoalDetails =  'assets/images/unselectedGoalDetails.png';
  static const String userDummy =  'assets/images/userDummy.png';
  static const String maleWhite =  'assets/images/maleWhite.png';

  static const String editProfile =  'assets/images/editProfile.png';
  static const String feedbacks =  'assets/images/feedbacks.png';
  static const String fitnessGoal =  'assets/images/fitnessGoal.png';
  static const String logOut =  'assets/images/logOut.png';
  static const String myCard =  'assets/images/myCard.png';
  static const String rateUs =  'assets/images/rateUs.png';
  static const String referAFriend =  'assets/images/referAFriend.png';
  static const String settings =  'assets/images/settings.png';
  static const String logOutProfile =  'assets/images/logOutProfile.png';
  static const String cardBG =  'assets/images/cardBG.png';
  static const String visaLogo = 'assets/images/visaLogo.png';
  static const String deleteCard = 'assets/images/deleteCard.png';

  static const String heart = 'assets/images/heart.png';
  static const String drop = 'assets/images/drop.png';
  static const String steps = 'assets/images/steps.png';
  static const String calculator = 'assets/images/calculator.png';
  static const String reload = 'assets/images/reload.png';
  static const String worktOutSet = 'assets/images/WorktOutSet.png';
  static const String logoImage_122 = 'assets/images/logoImage_122.png';
}



