

name: alfa
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  
  cupertino_icons: ^0.1.3
  fluttertoast: ^3.1.3
  logging: ^0.11.4
  page_view_indicators: ^1.3.1
  flutter_statusbarcolor: ^0.2.3
  country_code_picker: ^1.2.3
  flutter_page_indicator: ^0.0.3
  pin_entry_text_field: ^0.1.4
  ink_page_indicator: ^0.1.2
  flare_splash_screen: ^2.0.1+2
  stretchy_header: ^1.0.8
  intl: ^0.16.1
  image_picker: ^0.6.1+10
  jiffy: ^3.0.1
  g2x_week_calendar: ^0.1.7
  flutter_swiper: ^1.1.6
  stop_watch_timer: ^0.4.0
  video_player: ^0.10.11+2
  share: ^0.6.4+3
  rate_in_store: ^0.0.1
  google_sign_in: ^4.1.1
  flutter_facebook_login: ^3.0.0
#  flutter_facebook_auth: ^0.3.2
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.6
  firebase_messaging: ^6.0.16
  toast: ^0.1.5
  flutter_webview_plugin: ^0.3.10+1
  dart_notification_center: ^1.0.0+1
  percent_indicator: ^2.1.5
#  flick_video_player: ^0.1.1
  url_launcher: ^5.5.3
  flutter_calendar_carousel: ^1.4.0
  keyboard_actions: ^3.3.0
  health: ^2.0.4+1
  http: ^0.12.2
  youtube_player_flutter: ^7.0.0+7


dev_dependencies:
  flutter_launcher_icons: "^0.8.0"

  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/ic_logo.png
    - assets/images/intro.png
    - assets/images/ic_google.png
    - assets/images/ic_facebook.png
    - assets/images/ic_back.png
    - assets/images/ic_profile.png
    - assets/images/ic_male.png
    - assets/images/ic_male_new.png
    - assets/images/ic_female.png
    - assets/images/ic_notification.png
    - assets/images/ic_right_arrow.png
    - assets/images/ic_tint.png
    - assets/images/ic_setting.png
    - assets/images/ic_add_card.jpg
    - assets/images/emailSent.png
    - assets/images/maleUnselectet.png
    - assets/images/femaleUnselected.png
    - assets/images/profile.png
    - assets/images/track.png
    - assets/images/foodDiary.png
    - assets/images/goals.png
    - assets/images/workouts.png
    - assets/images/selctedWorkouts.png
    - assets/images/selectedProfile.png
    - assets/images/selectedTrac.png
    - assets/images/selectedFoodDiary.png
    - assets/images/selectedGoals.png
    - assets/images/notifications.png
    - assets/images/upper.png
    - assets/images/fullBody.png
    - assets/images/core.png
    - assets/images/lowerBody.png
    - assets/images/quete.png
    - assets/images/play.png
    - assets/images/ImageThumbnailVideo.png
    - assets/images/upNext.png
    - assets/images/pause.png
    - assets/images/play-button.png
    - assets/images/goalList.png
    - assets/images/add_Image.png
    - assets/images/unselectedGoalDetails.png
    - assets/images/selectedGoalsDetails.png
    - assets/images/userDummy.png
    - assets/images/maleWhite.png
    - assets/images/editProfile.png
    - assets/images/feedbacks.png
    - assets/images/fitnessGoal.png
    - assets/images/logOut.png
    - assets/images/myCard.png
    - assets/images/rateUs.png
    - assets/images/referAFriend.png
    - assets/images/settings.png
    - assets/images/logOutProfile.png
    - assets/images/cardBG.png
    - assets/images/visaLogo.png
    - assets/images/deleteCard.png
    - assets/images/heart.png
    - assets/images/drop.png
    - assets/images/steps.png
    - assets/images/calculator.png
    - assets/images/reload.png
    - assets/images/WorktOutSet.png
    - assets/images/logoImage_122.png



  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Black.ttf
        - asset: assets/font/Poppins-Bold.ttf
        - asset: assets/font/Poppins-ExtraBold.ttf
        - asset: assets/font/Poppins-ExtraLight.ttf
        - asset: assets/font/Poppins-Light.ttf
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-SemiBold.ttf
        - asset: assets/font/Poppins-Medium.ttf


#      fonts:
#        - asset: assets/font/kollektif.ttf
#    - family: kollektif_bold
#      fonts:
#        - asset: assets/font/kollektif_bold.ttf
#    - family: kollektif_bolditalic
#      fonts:
#        - asset: assets/font/kollektif_bolditalic.ttf
#    - family: kollektif_iitalic
#      fonts:
#        - asset: assets/font/kollektif_iitalic.ttf
#    - family: CustomIcons
#      fonts:
#        - asset: assets/font/CustomIcons.ttf

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

